### ISSUE TITLE
Extra damage is not added on Crit

### ISSUE THREAD

**Issue by Dew314** [chrisesharp/foundryvtt-helveczia#3]
If a weapon has a "+ X" on damage, it is added automaticaly on normal succesful attacks, but it is not added on a Crit.
I attach the Stiletto as an example:
![kép](https://user-images.githubusercontent.com/20098579/212317775-29f971b1-2284-479e-ac7f-15749c9e1be0.png)

**Comment by chrisesharp** [comment]
Hi @Dew314 - firstly, thanks for raising an issue...I thought I was the only person using this system! :-)

I took a look and it seems to be working fine for me...can you let me know which version you have installed? It should be 2.0.7 (you should be able to just hit "Update" in Foundry)

**Comment by Dew314** [comment]
Foundry version is 10.288, because above it alerted me for compatibility issues with Helvéczia, and the Helvéczia version is indeed 2.0.7

**Comment by Dew314** [comment]
I just realised that the extra damage is not coming from the weapon, it came from the STR bonusz I guess :D . Not sure if it makes any difference though.

**Comment by Dew314** [comment]
it works with normal succes:
![kép](https://user-images.githubusercontent.com/20098579/212658742-07a87022-8c5e-4760-938a-357ee1a39f2c.png)

**Comment by chrisesharp** [comment]
Hmm, I am flumoxed! I cannot reproduce the problem. I tried with a character and a NPC (to check there wasn't a difference) , I added STR and level bonuses (to check all were being added), and got the same behaviour with each:
<img width="285" alt="Screenshot 2023-01-16 at 14 43 35" src="https://user-images.githubusercontent.com/13590524/212705366-046d79a3-268e-4141-9f68-3d8d22e0fce2.png">
<img width="285" alt="Screenshot 2023-01-16 at 14 43 55" src="https://user-images.githubusercontent.com/13590524/212705418-8bf05fab-e4df-41fb-8482-b5a5cb990fae.png">

Are you running locally or in the Forge? Not sure if or why that would make a difference, but I'm struggling to think what else might affect it.

**Comment by Dew314** [comment]
Sorry, I think I found the problem. It seems there is no problem :D On my example the damage looks like this:
![image](https://user-images.githubusercontent.com/20098579/212716494-850f1f0d-1988-443e-9274-03e53053c13d.png)
I thought the damage is 2, and it should be 3 if we add the +1. But in the final result it shows, that the damage is 3, and it is multiplied by 2 because of the crit. I thought it was multiplied by 3 :D
So, I think we can close this, there is no issue.

**Comment by chrisesharp** [comment]
Ah! Yes, of course! Well, I didn't spot that either :-) 

Thank you, and I hope you are enjoying the system!
