### ISSUE TITLE
System webpage and other questions

### ISSUE THREAD

**Issue by Dew314** [chrisesharp/foundryvtt-helveczia#6]
Hi! There is a strange anomaly about the system's webpage (https://chrisesharp.github.io/foundryvtt-helveczia/) that only occur in firefox browser. I works perfectly in Edge.
The menu bar is not fitting in Firefox, and if you scrolls down, it goes into the body of the page. Let me show you in screenshots:
Firefox:
![kép](https://user-images.githubusercontent.com/20098579/218252130-14766ea4-88e2-4c03-a8f4-916faa812a62.png)
![kép](https://user-images.githubusercontent.com/20098579/218252166-788cd12b-b17e-43e9-ad7f-8c52e7e95f38.png)

And it works perfectly in edge:
![kép](https://user-images.githubusercontent.com/20098579/218252181-e682c5b0-a6ef-4938-92c2-4a255ae2ebb2.png)

Other questions: how can I contact you with questions and ideas about the Foundry Helvéczia system, if they are not issue related? :D I could not find such option here in github.

**Comment by chrisesharp** [comment]
Hi @Dew314 - how odd...not sure why that wa only appearing in Firefox...anyway, should be fixed now.

Re: contacting me for other ideas  and questions - you can add a suitable `label` to an issue (on the right hand side), so I can see them as such.
